# Generated by Django 5.0.3 on 2025-04-11 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_create_eventregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsArticle",
        ),
    ]
