# Generated by Django 5.0.3 on 2025-04-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_slot",
                to="appointments.appointment",
            ),
        ),
    ]
