# Generated by Django 5.0.3 on 2025-04-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_timeslot_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Brief description of the reason for appointment",
                null=True,
            ),
        ),
    ]
